-- 0002_seed_opportunities.sql
-- Seed opportunities matching the frontend mock data

INSERT INTO opportunities (id, title, organization, category, category_label, deadline, location, format, eligibility, description, requirements, timeline, color, recommended, website) VALUES
(
    'kuanysh-forum',
    'Kuanysh STEM Forum',
    'Kuanysh Foundation',
    'forum',
    'Форум',
    '2026-10-02',
    'Алматы',
    'offline',
    '9–11 класс, интерес к точным наукам',
    'Двухдневный форум для школьников, увлечённых STEM: лекции от инженеров и исследователей, практические лаборатории и питчи собственных проектов перед менторами.',
    ARRAY['Анкета участника', 'Короткое эссе о своём STEM-проекте (необязательно)', 'Согласие родителей для участников младше 18 лет'],
    '[{"label": "Приём заявок", "date": "до 25 сентября"}, {"label": "Отбор участников", "date": "28 сентября"}, {"label": "Форум", "date": "2–3 октября"}]'::jsonb,
    'red',
    true,
    'https://example.org/kuanysh-forum'
),
(
    'nazgul-forum',
    'Nazgul Forum',
    'Nazgul Youth Initiative',
    'forum',
    'Форум',
    '2026-09-20',
    'Алматы',
    'offline',
    '10–11 класс',
    'Форум молодых лидеров, посвящённый устойчивому развитию и социальному предпринимательству в Центральной Азии.',
    ARRAY['Мотивационное письмо', 'Резюме на одну страницу'],
    '[{"label": "Приём заявок", "date": "до 15 сентября"}, {"label": "Форум", "date": "20 сентября"}]'::jsonb,
    'red',
    false,
    'https://example.org/nazgul-forum'
),
(
    'aimun-volunteer',
    'AIMUN Volunteer Programme',
    'Almaty International MUN',
    'volunteering',
    'Волонтёрство',
    '2026-09-30',
    'Алматы',
    'hybrid',
    'Любой класс, английский язык от Intermediate',
    'Волонтёрская программа модели ООН: логистика, работа с делегатами, помощь секретариату. Официальный сертификат участника по итогам конференции.',
    ARRAY['Анкета волонтёра', 'Собеседование (15 минут)'],
    '[{"label": "Приём заявок", "date": "до 30 сентября"}, {"label": "Собеседования", "date": "1–3 октября"}, {"label": "Конференция", "date": "12:00–14:00, 19–20 октября"}]'::jsonb,
    'yellow',
    true,
    'https://example.org/aimun'
),
(
    'ictj-olympiad',
    'ICTJ Olympiad',
    'International Committee for Talented Youth',
    'olympiad',
    'Физ-Мат Олимпиада',
    '2026-10-14',
    'Онлайн',
    'online',
    '8–11 класс',
    'Международная олимпиада по физике и математике в два тура: отборочный онлайн-тур и финал с сертификатом международного образца.',
    ARRAY['Регистрация на платформе', 'Отборочный тур (2 часа)'],
    '[{"label": "Отборочный тур", "date": "14 октября, 12:00–14:00"}, {"label": "Финал", "date": "9 ноября"}]'::jsonb,
    'blue',
    false,
    'https://example.org/ictj'
),
(
    'almaty-fest',
    'Almaty Fest Volunteering',
    'Almaty City Events',
    'volunteering',
    'Волонтёрство',
    '2026-09-10',
    'Алматы',
    'offline',
    '14+ лет',
    'Волонтёрская команда городского фестиваля: навигация гостей, помощь на сценах и работа с инвентарём. Отличная возможность получить первый опыт волонтёрства.',
    ARRAY['Анкета', 'Инструктаж перед мероприятием'],
    '[{"label": "Приём заявок", "date": "до 10 сентября"}, {"label": "Фестиваль", "date": "6:00–10:00, 20 сентября"}]'::jsonb,
    'blue',
    false,
    'https://example.org/almaty-fest'
),
(
    'be-together',
    'Be Together',
    'Together Kazakhstan',
    'volunteering',
    'Волонтёрство',
    '2026-09-25',
    'Алматы',
    'offline',
    'Любой класс',
    'Регулярная волонтёрская программа помощи детским домам: образовательные мастер-классы и совместные активности раз в две недели.',
    ARRAY['Анкета', 'Собеседование с координатором'],
    '[{"label": "Набор волонтёров", "date": "до 25 сентября"}, {"label": "Первая смена", "date": "8:00–10:00, 27 сентября"}]'::jsonb,
    'red',
    false,
    'https://example.org/be-together'
),
(
    'formula-buildathon',
    'Формула Buildathon',
    'QazTech Youth',
    'hackathon',
    'Хакатон',
    '2026-10-05',
    'Алматы',
    'offline',
    '9–11 класс, базовые навыки программирования',
    '48-часовой хакатон для школьных команд: построить прототип продукта, решающего локальную городскую проблему. Менторы из индустрии и призовой фонд для трёх лучших команд.',
    ARRAY['Команда из 2–4 человек', 'Заявка с идеей проекта'],
    '[{"label": "Регистрация команд", "date": "до 5 октября"}, {"label": "Хакатон", "date": "17–19 октября"}]'::jsonb,
    'violet',
    true,
    'https://example.org/formula-buildathon'
),
(
    'silkroad-research',
    'Silk Road Research Fellowship',
    'Central Asia Studies Institute',
    'research',
    'Исследование',
    '2026-11-01',
    'Онлайн',
    'online',
    '10–11 класс, интерес к истории и социальным наукам',
    'Восьминедельная исследовательская стажировка под руководством университетского научного руководителя. Итог — короткая исследовательская работа, которую можно включить в портфолио.',
    ARRAY['Мотивационное письмо', 'Пример письменной работы'],
    '[{"label": "Приём заявок", "date": "до 1 ноября"}, {"label": "Начало программы", "date": "17 ноября"}]'::jsonb,
    'yellow',
    false,
    'https://example.org/silkroad-fellowship'
),
(
    'greenfuture-internship',
    'GreenFuture Internship',
    'EcoVision Kazakhstan',
    'internship',
    'Стажировка',
    '2026-09-18',
    'Алматы',
    'hybrid',
    '10–11 класс',
    'Оплачиваемая стажировка в отделе устойчивого развития: сбор данных по качеству воздуха и участие в подготовке городского экологического отчёта.',
    ARRAY['Резюме', 'Короткое собеседование'],
    '[{"label": "Приём заявок", "date": "до 18 сентября"}, {"label": "Стажировка", "date": "5 недель, с 1 октября"}]'::jsonb,
    'blue',
    false,
    'https://example.org/greenfuture'
),
(
    'national-merit-scholarship',
    'National Merit Scholarship',
    'Bilim Foundation',
    'scholarship',
    'Стипендия',
    '2026-12-01',
    'По всему Казахстану',
    'online',
    '11 класс, средний балл от 4.5',
    'Ежегодная стипендия для выпускников с сильной академической историей и активной внеучебной деятельностью, покрывающая часть стоимости обучения в вузе.',
    ARRAY['Транскрипт оценок', 'Портфолио внеучебной деятельности', 'Эссе'],
    '[{"label": "Приём заявок", "date": "до 1 декабря"}, {"label": "Результаты", "date": "20 января"}]'::jsonb,
    'red',
    false,
    'https://example.org/national-merit'
)
ON CONFLICT (id) DO NOTHING;
